-- Initial PostgreSQL schema for the Fake University source of truth.
--
-- This intentionally mirrors the current SQLite UniversityStore shape. The
-- API/backend remains the only access boundary; browser roles receive no
-- privileges or RLS policies on these tables.

create table public.students (
  student_id text primary key,
  profile_json jsonb not null,
  record_json jsonb not null,
  updated_at timestamptz not null
);

create table public.courses (
  course_code text primary key,
  data_json jsonb not null,
  updated_at timestamptz not null
);

create table public.offerings (
  section_id text primary key,
  course_code text not null,
  term_code text not null,
  data_json jsonb not null,
  updated_at timestamptz not null
);

create index offerings_term_course_idx
  on public.offerings (term_code, course_code);

create table public.calendar (
  id smallint primary key,
  data_json jsonb not null,
  updated_at timestamptz not null,
  constraint calendar_singleton_check check (id = 1)
);

create table public.academic_dates (
  date_id text primary key,
  data_json jsonb not null,
  updated_at timestamptz not null
);

create table public.events (
  cursor bigint generated by default as identity primary key,
  id text not null unique,
  event_type text not null,
  version integer not null,
  occurred_at timestamptz not null,
  student_id text,
  payload_json jsonb not null,
  idempotency_key text not null unique,
  delivered_at timestamptz,
  attempts integer not null default 0,
  next_attempt_at timestamptz not null,
  last_status integer
);

-- Supports the webhook worker's pending-event scan. Cursor, event id, and
-- idempotency-key lookups are already covered by the primary/unique indexes.
create index events_pending_delivery_idx
  on public.events (next_attempt_at, cursor)
  where delivered_at is null;

create table public.aggregate_versions (
  aggregate_key text primary key,
  version integer not null
);

alter table public.students enable row level security;
alter table public.courses enable row level security;
alter table public.offerings enable row level security;
alter table public.calendar enable row level security;
alter table public.academic_dates enable row level security;
alter table public.events enable row level security;
alter table public.aggregate_versions enable row level security;

-- No anon/authenticated policies are created. The revokes also prevent direct
-- Data API access if these public-schema tables are exposed by project settings.
revoke all privileges on table public.students from anon, authenticated;
revoke all privileges on table public.courses from anon, authenticated;
revoke all privileges on table public.offerings from anon, authenticated;
revoke all privileges on table public.calendar from anon, authenticated;
revoke all privileges on table public.academic_dates from anon, authenticated;
revoke all privileges on table public.events from anon, authenticated;
revoke all privileges on table public.aggregate_versions from anon, authenticated;
revoke all privileges on sequence public.events_cursor_seq from anon, authenticated;

-- The Fake University backend may use a server-only service-role key. That key
-- must never be exposed to browser code or to the Morshidi backend/client.
grant select, insert, update, delete on table public.students to service_role;
grant select, insert, update, delete on table public.courses to service_role;
grant select, insert, update, delete on table public.offerings to service_role;
grant select, insert, update, delete on table public.calendar to service_role;
grant select, insert, update, delete on table public.academic_dates to service_role;
grant select, insert, update, delete on table public.events to service_role;
grant select, insert, update, delete on table public.aggregate_versions to service_role;
grant usage, select on sequence public.events_cursor_seq to service_role;
